version: '3.8'

services:
  app:
    image: 'backend'
    build:
      context: .
    container_name: app
    depends_on:
      - my-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=malik
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/twitter
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=malik
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  my-postgres:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=malik
      - POSTGRES_DB=twitter
    ports:
      - "5432:5432"